apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: update-version-taskrun-  
spec:
  taskRef:
    name: update-version
  workspaces:
  - name: code-source
    persistentvolumeclaim:
      claimName: code-source-pvc
  - name: ssh-directory
    secret:
      secretName: git-credentials
  - name: iac-source
    persistentvolumeclaim:
      claimName: iac-source-pvc     
  serviceAccountName: pipeline-service-account
  params:
  - name: iacRepositoryUrl
    value: git@github.com:corollo/demo-app-iac.git    
