apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
    params:
      - name: url
        type: string
      - name: revision
        type: string
        default: main
      - name: path
        type: string
        default: /workspace/source
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        git clone --branch $(inputs.params.revision) $(inputs.params.url) $(inputs.params.path)