apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: node-build
spec:
  workspaces:
    - name: source
      description: The workspace consisting of maven project.
  steps:
    - name: node-build
      image: node:lts-alpine
      workingDir: /workspace/source   
      script: |
        #!/usr/bin/env sh
        set -eu
        
        echo "# node build"
        npm ci
