apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: semantic-release
spec:
  workspaces:
    - name: source
    - name: ssh-directory
  params:
    - name: verbose
      description: Log the commands that are executed during the operation.
      type: string
      default: "true"
    - name: userHome
      description: Absolute path to the user's home directory.
      type: string
      default: "/root"  
    - name: repositoryUrl
      description: the project repository Url 
      type: string
      default: ""
    - name: githubToken
      description: github token
      type: string
      default: ""
  steps:
    - name: semantic-release
      image: corollo/semantic-node-git:1.0.0
      workingDir: /workspace/source
      env:
      - name: PARAM_USER_HOME
        value: $(params.userHome)      
      - name: PARAM_VERBOSE
        value: $(params.verbose)      
      - name: WORKSPACE_SSH_DIRECTORY_BOUND
        value: $(workspaces.ssh-directory.bound)
      - name: WORKSPACE_SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)
      - name: REPOSITORY_URL
        value: $(params.repositoryUrl)
      - name: GITHUB_TOKEN
        value: $(params.githubToken)
      - name: DOCKER_HOST
        value: tcp://localhost:2375                
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "${PARAM_VERBOSE}" = "true" ] ; then
          set -x
        fi

        echo "# set ssh credential for git"
        if [ "${WORKSPACE_SSH_DIRECTORY_BOUND}" = "true" ] ; then
          cp -R "${WORKSPACE_SSH_DIRECTORY_PATH}" "${PARAM_USER_HOME}"/.ssh
          chmod 700 "${PARAM_USER_HOME}"/.ssh
          chmod -R 400 "${PARAM_USER_HOME}"/.ssh/*
        fi

        echo "check git status"
        #git checkout pre/beta
        git status

        export CI=true

        echo "# install semantic plugin"
        npm install @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github @semantic-release/exec @semantic-release/changelog conventional-changelog-conventionalcommits --force --no-save        
        
        echo "# run semantic-release "
        npx semantic-release@20 --repository-url ${REPOSITORY_URL}
        echo "end"
