apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: semantic-release
spec:
  workspaces:
    - name: source
    - name: ssh-directory
  params:
    - name: verbose
      description: Log the commands that are executed during the operation.
      type: string
      default: "false"
    - name: userHome
      description: Absolute path to the user's home directory.
      type: string
      default: "/root"  
    - name: repositoryUrl
      description: the project repository Url 
      type: string
      default: ""
    - name: githubToken
      description: github token
      type: string
      default: ""
    - name: ciRegistry
      description: ci registry base url
      type: string
      default: ""
    - name: ciRegistryUser
      description: ci registry username
      type: string
      default: ""
    - name: ciRegistryPass
      description: ci registry user password/token
      type: string
      default: ""      
    - name: ciImageName
      description: ci registry Image
      type: string
      default: "demo-app"       
  steps:
    - name: semantic-release
      image: corollo/semantic-node-git:1.0.0
      workingDir: /workspace/source
      env:
      - name: PARAM_USER_HOME
        value: $(params.userHome)      
      - name: PARAM_VERBOSE
        value: $(params.verbose)      
      - name: WORKSPACE_SSH_DIRECTORY_BOUND
        value: $(workspaces.ssh-directory.bound)
      - name: WORKSPACE_SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)
      - name: REPOSITORY_URL
        value: $(params.repositoryUrl)
      - name: GITHUB_TOKEN
        value: $(params.githubToken)
      - name: CI
        value: 'true'
      - name: DOCKER_HOST
        value: tcp://localhost:2376
      - name: DOCKER_TLS_VERIFY
        value: '1'
      - name: DOCKER_CERT_PATH
        value: /certs/client
      - name: CI_REGISTRY
        value: $(params.ciRegistry)
      - name: CI_IMAGE_NAME
        value: $(params.ciImageName)
      - name: CI_REGISTRY_USER
        value: $(params.ciRegistryUser)
      envFrom:
        - secretRef:
            name: registry-pass-secrets
        - secretRef:
            name: git-token-secrets
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "${PARAM_VERBOSE}" = "true" ] ; then
          set -x
        fi

        echo "# set ssh credential for git"
        if [ "${WORKSPACE_SSH_DIRECTORY_BOUND}" = "true" ] ; then
          cp -R "${WORKSPACE_SSH_DIRECTORY_PATH}" "${PARAM_USER_HOME}"/.ssh
          chmod 700 "${PARAM_USER_HOME}"/.ssh
          chmod -R 400 "${PARAM_USER_HOME}"/.ssh/*
        fi
         
        export CI_REGISTRY_IMAGE=$CI_REGISTRY/$CI_IMAGE_NAME

        echo "# run docker login on dockerhub user $CI_REGISTRY_USER"
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS
        echo "# run docker build $CI_REGISTRY_IMAGE:latest "
        docker build -t $CI_REGISTRY_IMAGE:latest .

        echo "# run install semantic plugin"
        npm install @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github @semantic-release/exec @semantic-release/changelog conventional-changelog-conventionalcommits --force --no-save
        echo "# run semantic-release "
        npx semantic-release@20 --repository-url ${REPOSITORY_URL}

        echo "# run docker push $CI_REGISTRY_IMAGE:latest "
        docker push $CI_REGISTRY_IMAGE:latest

        echo "end"
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
  sidecars:
    - image: docker:dind
      name: server
      args:
        - --storage-driver=vfs
        - --userland-proxy=false
        - --debug
      securityContext:
        privileged: true
      env:
      # Write generated certs to the path shared with the client.
      - name: DOCKER_TLS_CERTDIR
        value: /certs
      volumeMounts:
      - mountPath: /certs/client
        name: dind-certs
      # Wait for the dind daemon to generate the certs it will share with the
      # client.
      readinessProbe:
        periodSeconds: 1
        exec:
          command: ['ls', '/certs/client/ca.pem']
  volumes:
  - name: dind-certs
    emptyDir: {}
