apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-version
spec:
  workspaces:
    - name: code-source
    - name: iac-source
    - name: ssh-directory
  params:
    - name: iacRepositoryUrl
      description: Git repository containing manifest files to update
    - name: userHome
      description: Absolute path to the user's home directory.
      type: string
      default: "/root"      
  steps:
    # - name: get-latest-tag
    #   image: alpine/git
    #   workingDir: /workspace/code-source
    #   script: |
    #     #!/usr/bin/env sh
    #     set -x
    #     ls -l
    #     # Recupera l'ultimo tag
    #     latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
    #     echo "Latest Tag: $latest_tag"
    #     echo "export latest_tag=$latest_tag" > /workspace/iac-source/latest_tag.env      
    - name: clone-iac-repo
      image: alpine/git
      workingDir: /workspace/iac-source
      env:
      - name: IAC_REPOSITORY_URL
        value: $(params.iacRepositoryUrl)
      - name: PARAM_USER_HOME
        value: $(params.userHome)
      - name: WORKSPACE_SSH_DIRECTORY_BOUND
        value: $(workspaces.ssh-directory.bound)
      - name: WORKSPACE_SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)         
      script: |
        #!/usr/bin/env sh
        set -x

        export projectDir=./demo-app-iac
        export versionFile=/workspace/code-source/latest_tag.env

        # controllo se esiste il file della versione
        if [ -e "${versionFile}" ]; then
  
          echo "recupero la nuova versione dal file ${versionFile}"
          source /workspace/code-source/latest_tag.env
          echo "get the latest_tag: ${latest_tag}"

          if [[ ${latest_tag} == *"beta"* ]]; then
  
            if [ "${WORKSPACE_SSH_DIRECTORY_BOUND}" = "true" ] ; then
              cp -R "${WORKSPACE_SSH_DIRECTORY_PATH}" "${PARAM_USER_HOME}"/.ssh
              chmod 700 "${PARAM_USER_HOME}"/.ssh
              chmod -R 400 "${PARAM_USER_HOME}"/.ssh/*
            fi

            # controlla se esiste un vecchio clone e nel caso lo cancella
            if [ -d "${projectDir}" ]; then
              echo "clean dir ${projectDir}"
              rm -r "${projectDir}"
            fi

            # Clona il repository IaC
            git clone ${IAC_REPOSITORY_URL} 
            cd ${projectDir}

            #
            sed -i "s/^  tag: .*/  tag: \"${latest_tag}\"/" env/dev.values.yaml

            git config --global user.email "tekton@fake.com"
            git config --global user.name "tekton-update-version-task"

            git add env/dev.values.yaml
            git commit -m "update tag version (${latest_tag}) in file env/dev.values.yaml"
            git push

          else
            echo "Il file della versione[${versionFile}] esiste, ma non è di sviluppo [beta], skip update iac"
          fi
        else
          echo "Il file della versione[${versionFile}] non esiste, skip update iac"
        fi    
