apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trigger-demo-ingress
  namespace: demo-trigger
spec:
  rules:
    - http:
        paths:
          - path: /trigger-demo
            pathType: Prefix
            backend:
              service:
                name: el-trigger-demo-el
                port:
                  number: 8080