apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-dev
spec:
  destination:
    namespace: demo-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - env/prod.values.yaml
    path: . 
    repoURL: https://github.com/corollo/demo-app-iac
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true