apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: semantic-release-ci-
spec:
  pipelineRef:
    name: semantic-release-ci 
  serviceAccountName: pipeline-service-account
  params:
  - name: repo-url
    value: git@github.com:subzero-team/demo-app.git
  - name: revision
    value: pre/beta
  - name: repositoryUrl
    value: https://github.com/subzero-team/demo-app.git
  - name: iacRepositoryUrl
    value: git@github.com:subzero-team/demo-app-iac.git
  - name: ciRegistry
    value: corollo
  - name: ciRegistryUser
    value: corollo
  workspaces:
  - name: code-source-data
    persistentvolumeclaim:
      claimName: code-source-pvc
  - name: iac-source-data
    persistentvolumeclaim:
      claimName: iac-source-pvc      
  - name: git-credentials
    secret:
      secretName: git-credentials
  - name: docker-storage
    persistentvolumeclaim:
      claimName: docker-storage-pvc     