apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: semantic-release-ci-
spec:
  pipelineRef:
    name: semantic-release-ci
  workspaces:
  - name: code-source-data
    persistentvolumeclaim:
      claimName: code-source-pvc
  - name: iac-source-data
    persistentvolumeclaim:
      claimName: iac-source-pvc      
  - name: git-credentials
    secret:
      secretName: git-credentials
  serviceAccountName: pipeline-service-account
  params:
  - name: repo-url
    value: git@github.com:corollo/demo-app.git
  - name: revision
    value: main
  - name: repositoryUrl
    value: "https://github.com/corollo/demo-app.git"
  - name: iacRepositoryUrl
    value: git@github.com:corollo/demo-app-iac.git