apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: semantic-release-ci
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  - name: revision
    type: string
    description: The git revision to clone from.    
  workspaces:
  - name: shared-data
  - name: git-credentials
  - name: maven-settings
  - name: maven-local-m2
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.revision)
  - name: maven-run
    taskRef:
      name: maven
    runAfter:
      - fetch-source
    params:
    - name: GOALS
      value:
        - -DskipTests
        - clean
        - package
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: shared-data
    - name: maven-local-repo
      workspace: maven-local-m2
  - name: semantic-release
    runAfter: ["maven-run"]
    taskRef:
      name: semantic-release
    workspaces:
    - name: source
      workspace: shared-data
    - name: ssh-directory
      workspace: git-credentials
      