apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: semantic-release-ci
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  - name: revision
    type: string
    description: The git revision to clone from.    
  - name: repositoryUrl
    type: string
    description: The git repo URL to clone from.
  - name: iacRepositoryUrl
    type: string
    description: The git repo URL to clone from.
  - name: githubToken
    type: string
    description: github token
  workspaces:
  - name: code-source-data
  - name: iac-source-data
  - name: git-credentials
  - name: docker-storage
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: code-source-data
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.revision)
  - name: node-build
    taskRef:
      name: node-build
    runAfter:
      - fetch-source
    workspaces:
    - name: source
      workspace: code-source-data    
  - name: semantic-release
    runAfter: ["node-build"]
    taskRef:
      name: semantic-release
    workspaces:
    - name: source
      workspace: code-source-data
    - name: ssh-directory
      workspace: git-credentials 
    params:
    - name: repositoryUrl
      value: $(params.repositoryUrl)
    - name: githubToken
      value: $(params.githubToken)
  - name: update-version
    runAfter: ["semantic-release"]
    taskRef:
      name: update-version
    workspaces:
    - name: code-source
      workspace: code-source-data
    - name: iac-source
      workspace: iac-source-data
    - name: ssh-directory
      workspace: git-credentials   
    params:
    - name: iacRepositoryUrl
      value: $(params.iacRepositoryUrl)      